import {
  Agency,
  AuditEvent,
  Client,
  ComplianceFlag,
  ConsentRecord,
  Conversation,
  ConversationMessage,
  DemoDataState,
  FollowupWorkflow,
  OpportunitySignal,
  QaReview,
  Task,
  TranscriptSummary,
  User
} from "@/lib/types";

const agency: Agency = {
  id: "agency-1",
  name: "Harbor Senior Market Operations",
  slug: "harbor-senior-market-operations",
  timezone: "America/Chicago",
  region: "South Central"
};

const users: User[] = [
  { id: "user-1", agencyId: agency.id, fullName: "Dana Brooks", role: "manager", licenseType: "life_health", email: "dana.brooks@example.com", team: "Operations" },
  { id: "user-2", agencyId: agency.id, fullName: "Alex Rivera", role: "agent", licenseType: "medicare_only", email: "alex.rivera@example.com", team: "Medicare Sales" },
  { id: "user-3", agencyId: agency.id, fullName: "Mia Chen", role: "service", licenseType: "none", email: "mia.chen@example.com", team: "Client Service" },
  { id: "user-4", agencyId: agency.id, fullName: "Jordan Patel", role: "compliance", licenseType: "life_health", email: "jordan.patel@example.com", team: "Compliance" },
  { id: "user-5", agencyId: agency.id, fullName: "Riley Torres", role: "agent", licenseType: "life_health", email: "riley.torres@example.com", team: "Senior Market" },
  { id: "user-6", agencyId: agency.id, fullName: "Casey Monroe", role: "agent", licenseType: "life_health", email: "casey.monroe@example.com", team: "Retirement Follow-Up" }
];

const clients: Client[] = [
  { id: "client-001", agencyId: agency.id, firstName: "Margaret", lastName: "Ellis", dob: "1961-07-12", phone: "(214) 555-0101", email: "margaret.ellis@example.com", state: "TX", preferredContactMethod: "phone", status: "new_to_medicare", tags: ["turning-65"], note: "Asked for a turning-65 timeline review." },
  { id: "client-002", agencyId: agency.id, firstName: "Daniel", lastName: "Kim", dob: "1958-03-28", phone: "(405) 555-0102", email: "daniel.kim@example.com", state: "OK", preferredContactMethod: "email", status: "active_review", tags: ["medigap-review"], note: "Wants a Medigap review before the annual premium change." },
  { id: "client-003", agencyId: agency.id, firstName: "Patricia", lastName: "Boone", dob: "1954-11-09", phone: "(816) 555-0103", email: "patricia.boone@example.com", state: "MO", preferredContactMethod: "phone", status: "active_review", tags: ["part-d"], note: "Called about formulary changes and Part D timing." },
  { id: "client-004", agencyId: agency.id, firstName: "Harold", lastName: "Foster", dob: "1953-05-20", phone: "(469) 555-0104", email: "harold.foster@example.com", state: "TX", preferredContactMethod: "phone", status: "active_review", tags: ["ma-question"], note: "Requested a neutral explanation of Medicare Advantage versus supplement options." },
  { id: "client-005", agencyId: agency.id, firstName: "Elaine", lastName: "Mercer", dob: "1950-02-15", phone: "(913) 555-0105", email: "elaine.mercer@example.com", state: "KS", preferredContactMethod: "phone", status: "watch", tags: ["premium-increase"], note: "Concerned about a recent premium increase notice." },
  { id: "client-006", agencyId: agency.id, firstName: "Robert", lastName: "Callahan", dob: "1948-12-03", phone: "(312) 555-0106", email: "robert.callahan@example.com", state: "IL", preferredContactMethod: "phone", status: "watch", tags: ["spouse-loss"], note: "Spouse passed away recently and account service work is underway." },
  { id: "client-007", agencyId: agency.id, firstName: "Linda", lastName: "Navarro", dob: "1952-08-17", phone: "(214) 555-0107", email: "linda.navarro@example.com", state: "TX", preferredContactMethod: "text", status: "watch", tags: ["cd-maturing"], note: "Mentioned a CD maturing next quarter during a service check-in." },
  { id: "client-008", agencyId: agency.id, firstName: "Kenneth", lastName: "Yates", dob: "1951-09-04", phone: "(816) 555-0108", email: "kenneth.yates@example.com", state: "MO", preferredContactMethod: "phone", status: "watch", tags: ["income-concern"], note: "Raised a retirement income concern after a supplement review." },
  { id: "client-009", agencyId: agency.id, firstName: "Marilyn", lastName: "Shah", dob: "1956-01-22", phone: "(405) 555-0109", email: "marilyn.shah@example.com", state: "OK", preferredContactMethod: "email", status: "watch", tags: ["market-risk"], note: "Worried about market volatility and retirement drawdown risk." },
  { id: "client-010", agencyId: agency.id, firstName: "Susan", lastName: "Whitaker", dob: "1955-06-01", phone: "(469) 555-0110", email: "susan.whitaker@example.com", state: "TX", preferredContactMethod: "phone", status: "service_only", tags: ["service-call"], note: "Service-only caller with billing and address update needs." },
  { id: "client-011", agencyId: agency.id, firstName: "James", lastName: "Holloway", dob: "1957-10-13", phone: "(501) 555-0111", email: "james.holloway@example.com", state: "AR", preferredContactMethod: "phone", status: "active_review", tags: ["missing-doc"], note: "Missing document follow-up for an intake packet." },
  { id: "client-012", agencyId: agency.id, firstName: "Helen", lastName: "Park", dob: "1960-04-24", phone: "(312) 555-0112", email: "helen.park@example.com", state: "IL", preferredContactMethod: "email", status: "new_to_medicare", tags: ["turning-65"], note: "Scheduling her first turning-65 planning call." },
  { id: "client-013", agencyId: agency.id, firstName: "George", lastName: "Benton", dob: "1951-03-11", phone: "(214) 555-0113", email: "george.benton@example.com", state: "TX", preferredContactMethod: "phone", status: "active_review", tags: ["part-d"], note: "Wants to confirm how a formulary change affects his upcoming review." },
  { id: "client-014", agencyId: agency.id, firstName: "Carol", lastName: "Dorsey", dob: "1952-09-27", phone: "(405) 555-0114", email: "carol.dorsey@example.com", state: "OK", preferredContactMethod: "text", status: "watch", tags: ["budget-review"], note: "Budget pressure from premium changes and household expenses." },
  { id: "client-015", agencyId: agency.id, firstName: "Thomas", lastName: "Avery", dob: "1954-07-09", phone: "(913) 555-0115", email: "thomas.avery@example.com", state: "KS", preferredContactMethod: "phone", status: "active_review", tags: ["provider-access"], note: "Provider access question during supplement renewal." },
  { id: "client-016", agencyId: agency.id, firstName: "Janet", lastName: "Russo", dob: "1950-05-18", phone: "(816) 555-0116", email: "janet.russo@example.com", state: "MO", preferredContactMethod: "email", status: "service_only", tags: ["claims"], note: "Claims confusion and service follow-up only." },
  { id: "client-017", agencyId: agency.id, firstName: "Victor", lastName: "Haines", dob: "1956-12-30", phone: "(469) 555-0117", email: "victor.haines@example.com", state: "TX", preferredContactMethod: "phone", status: "active_review", tags: ["missing-packet"], note: "Renewal packet not returned; team is following up." },
  { id: "client-018", agencyId: agency.id, firstName: "Donna", lastName: "Fields", dob: "1953-01-14", phone: "(214) 555-0118", email: "donna.fields@example.com", state: "TX", preferredContactMethod: "phone", status: "watch", tags: ["premium-increase"], note: "Comparing affordability after a double-digit rate increase." },
  { id: "client-019", agencyId: agency.id, firstName: "Charles", lastName: "Monroe", dob: "1949-08-26", phone: "(312) 555-0119", email: "charles.monroe@example.com", state: "IL", preferredContactMethod: "phone", status: "service_only", tags: ["beneficiary-update"], note: "Requested beneficiary contact updates after a family change." },
  { id: "client-020", agencyId: agency.id, firstName: "Martha", lastName: "Quinn", dob: "1951-02-02", phone: "(816) 555-0120", email: "martha.quinn@example.com", state: "MO", preferredContactMethod: "phone", status: "watch", tags: ["spouse-loss"], note: "Needs service help after the loss of her spouse and has broader retirement questions." },
  { id: "client-021", agencyId: agency.id, firstName: "Leonard", lastName: "Price", dob: "1954-09-21", phone: "(469) 555-0121", email: "leonard.price@example.com", state: "TX", preferredContactMethod: "text", status: "watch", tags: ["cd-maturing"], note: "Brought up a CD renewal during a document request call." },
  { id: "client-022", agencyId: agency.id, firstName: "Deborah", lastName: "Knox", dob: "1950-06-19", phone: "(405) 555-0122", email: "deborah.knox@example.com", state: "OK", preferredContactMethod: "phone", status: "active_review", tags: ["medigap-review"], note: "Annual Medigap review with cost sensitivity." },
  { id: "client-023", agencyId: agency.id, firstName: "Paul", lastName: "Sandoval", dob: "1959-10-07", phone: "(214) 555-0123", email: "paul.sandoval@example.com", state: "TX", preferredContactMethod: "email", status: "new_to_medicare", tags: ["sep-timing"], note: "Asking about enrollment timing and SEP rules." },
  { id: "client-024", agencyId: agency.id, firstName: "Gloria", lastName: "Bennett", dob: "1955-03-03", phone: "(913) 555-0124", email: "gloria.bennett@example.com", state: "KS", preferredContactMethod: "phone", status: "watch", tags: ["market-risk"], note: "Volatility concerns surfaced during a routine supplement check." },
  { id: "client-025", agencyId: agency.id, firstName: "Norman", lastName: "Tate", dob: "1952-11-16", phone: "(816) 555-0125", email: "norman.tate@example.com", state: "MO", preferredContactMethod: "phone", status: "service_only", tags: ["document-request"], note: "Called in for a missing document and signature reminder." }
];

const conversations: Conversation[] = [
  { id: "conv-001", agencyId: agency.id, clientId: "client-001", ownerUserId: "user-2", channel: "phone", status: "in_review", startedAt: "2026-04-03T09:00:00-05:00", endedAt: "2026-04-03T09:24:00-05:00", summary: "Turning-65 intake call completed with recording consent and initial Medicare supplement questions.", medicareScope: "Turning 65 intake", routingState: "ready_to_route", detectedTopics: ["turning_65", "consent"], retirementInterestDetected: false, nextStep: "Queue for manager review and intake checklist." },
  { id: "conv-002", agencyId: agency.id, clientId: "client-001", ownerUserId: "user-3", channel: "service_call", status: "closed", startedAt: "2026-04-09T14:10:00-05:00", endedAt: "2026-04-09T14:18:00-05:00", summary: "Reminder call for the onboarding packet and birthday timeline documents.", medicareScope: "Service only", routingState: "complete", detectedTopics: ["service_call", "missing_document_follow_up"], retirementInterestDetected: false, nextStep: "Closed after reminder delivered." },
  { id: "conv-003", agencyId: agency.id, clientId: "client-002", ownerUserId: "user-5", channel: "phone", status: "routed", startedAt: "2026-04-04T10:15:00-05:00", endedAt: "2026-04-04T10:37:00-05:00", summary: "Annual Medigap review requested after notice of a premium increase.", medicareScope: "Medigap review", routingState: "ready_to_route", detectedTopics: ["medigap_review", "premium_increase"], retirementInterestDetected: false, nextStep: "Route to licensed review call." },
  { id: "conv-004", agencyId: agency.id, clientId: "client-003", ownerUserId: "user-2", channel: "phone", status: "in_review", startedAt: "2026-04-05T11:00:00-05:00", endedAt: "2026-04-05T11:21:00-05:00", summary: "Part D question about formulary changes and pharmacy access.", medicareScope: "Part D education", routingState: "awaiting_review", detectedTopics: ["part_d_question"], retirementInterestDetected: false, nextStep: "Confirm formulary note and send educational follow-up." },
  { id: "conv-005", agencyId: agency.id, clientId: "client-004", ownerUserId: "user-2", channel: "phone", status: "in_review", startedAt: "2026-04-05T13:30:00-05:00", endedAt: "2026-04-05T13:56:00-05:00", summary: "Client asked a neutral Medicare Advantage question during a supplement discussion.", medicareScope: "Medicare plan comparison education", routingState: "awaiting_review", detectedTopics: ["medicare_advantage_question", "compliance_review"], retirementInterestDetected: false, nextStep: "Compliance check before follow-up summary is sent." },
  { id: "conv-006", agencyId: agency.id, clientId: "client-005", ownerUserId: "user-5", channel: "phone", status: "new", startedAt: "2026-04-06T09:20:00-05:00", endedAt: "2026-04-06T09:38:00-05:00", summary: "Premium increase concern raised during a Medigap anniversary review.", medicareScope: "Medigap review", routingState: "blocked", detectedTopics: ["premium_increase", "consent"], retirementInterestDetected: false, nextStep: "Obtain refreshed SOA before continued review." },
  { id: "conv-007", agencyId: agency.id, clientId: "client-006", ownerUserId: "user-3", channel: "service_call", status: "closed", startedAt: "2026-04-06T15:15:00-05:00", endedAt: "2026-04-06T15:28:00-05:00", summary: "Service call after spouse passed away to update records and mailing preferences.", medicareScope: "Service only", routingState: "complete", detectedTopics: ["service_call", "spouse_passed_away"], retirementInterestDetected: false, nextStep: "Closed with service notes recorded." },
  { id: "conv-008", agencyId: agency.id, clientId: "client-006", ownerUserId: "user-5", channel: "phone", status: "routed", startedAt: "2026-04-12T10:05:00-05:00", endedAt: "2026-04-12T10:34:00-05:00", summary: "Follow-up Medicare review included questions about household income after the spouse loss.", medicareScope: "Medicare supplement review", routingState: "ready_to_route", detectedTopics: ["spouse_passed_away", "retirement_income_interest"], retirementInterestDetected: true, nextStep: "Keep Medicare review separate and open a consented follow-up workflow." },
  { id: "conv-009", agencyId: agency.id, clientId: "client-007", ownerUserId: "user-3", channel: "service_call", status: "closed", startedAt: "2026-04-07T08:40:00-05:00", endedAt: "2026-04-07T08:52:00-05:00", summary: "CD maturity came up during a service request about premium drafting.", medicareScope: "Service only", routingState: "complete", detectedTopics: ["service_call", "cd_maturing"], retirementInterestDetected: true, nextStep: "Document the signal and await separate consent before outreach." },
  { id: "conv-010", agencyId: agency.id, clientId: "client-008", ownerUserId: "user-2", channel: "phone", status: "routed", startedAt: "2026-04-07T11:10:00-05:00", endedAt: "2026-04-07T11:42:00-05:00", summary: "Medigap review led to broader retirement income concerns because of rising monthly costs.", medicareScope: "Medigap review", routingState: "ready_to_route", detectedTopics: ["medigap_review", "premium_increase", "retirement_income_interest"], retirementInterestDetected: true, nextStep: "Route Medicare notes separately and open a consent request for follow-up." },
  { id: "conv-011", agencyId: agency.id, clientId: "client-009", ownerUserId: "user-5", channel: "phone", status: "routed", startedAt: "2026-04-07T14:00:00-05:00", endedAt: "2026-04-07T14:26:00-05:00", summary: "Client mentioned market risk concerns while reviewing supplement affordability.", medicareScope: "Medigap review", routingState: "ready_to_route", detectedTopics: ["market_risk_concern", "retirement_income_interest"], retirementInterestDetected: true, nextStep: "Send separate consent invitation for a licensed follow-up conversation." },
  { id: "conv-012", agencyId: agency.id, clientId: "client-010", ownerUserId: "user-3", channel: "service_call", status: "closed", startedAt: "2026-04-08T09:45:00-05:00", endedAt: "2026-04-08T09:57:00-05:00", summary: "Service call to correct mailing address and confirm premium draft timing.", medicareScope: "Service only", routingState: "complete", detectedTopics: ["service_call"], retirementInterestDetected: false, nextStep: "Closed." },
  { id: "conv-013", agencyId: agency.id, clientId: "client-011", ownerUserId: "user-3", channel: "phone", status: "new", startedAt: "2026-04-08T10:20:00-05:00", endedAt: "2026-04-08T10:33:00-05:00", summary: "Missing document follow-up call for an intake packet that was not returned.", medicareScope: "Intake support", routingState: "blocked", detectedTopics: ["missing_document_follow_up", "consent"], retirementInterestDetected: false, nextStep: "Collect missing signature page and recording consent." },
  { id: "conv-014", agencyId: agency.id, clientId: "client-012", ownerUserId: "user-2", channel: "phone", status: "in_review", startedAt: "2026-04-08T13:05:00-05:00", endedAt: "2026-04-08T13:28:00-05:00", summary: "Turning-65 planning call covered enrollment timing and Medigap basics.", medicareScope: "Turning 65 intake", routingState: "ready_to_route", detectedTopics: ["turning_65"], retirementInterestDetected: false, nextStep: "Prepare summary and send checklist." },
  { id: "conv-015", agencyId: agency.id, clientId: "client-013", ownerUserId: "user-5", channel: "phone", status: "closed", startedAt: "2026-04-08T15:00:00-05:00", endedAt: "2026-04-08T15:19:00-05:00", summary: "Part D call resolved a formulary concern without further action.", medicareScope: "Part D education", routingState: "complete", detectedTopics: ["part_d_question"], retirementInterestDetected: false, nextStep: "Closed after explanation." },
  { id: "conv-016", agencyId: agency.id, clientId: "client-014", ownerUserId: "user-5", channel: "phone", status: "routed", startedAt: "2026-04-09T09:30:00-05:00", endedAt: "2026-04-09T09:58:00-05:00", summary: "Budget review on a premium increase turned into a retirement-income question.", medicareScope: "Medigap affordability review", routingState: "ready_to_route", detectedTopics: ["premium_increase", "retirement_income_interest"], retirementInterestDetected: true, nextStep: "Split out a separate follow-up workflow if consent is granted." },
  { id: "conv-017", agencyId: agency.id, clientId: "client-015", ownerUserId: "user-2", channel: "phone", status: "closed", startedAt: "2026-04-09T11:15:00-05:00", endedAt: "2026-04-09T11:34:00-05:00", summary: "Provider access question answered during a Medigap review.", medicareScope: "Medigap review", routingState: "complete", detectedTopics: ["medigap_review"], retirementInterestDetected: false, nextStep: "Closed." },
  { id: "conv-018", agencyId: agency.id, clientId: "client-016", ownerUserId: "user-3", channel: "service_call", status: "closed", startedAt: "2026-04-09T13:40:00-05:00", endedAt: "2026-04-09T13:55:00-05:00", summary: "Service call about claims confusion and duplicate billing notice.", medicareScope: "Service only", routingState: "complete", detectedTopics: ["service_call"], retirementInterestDetected: false, nextStep: "Closed after service note sent." },
  { id: "conv-019", agencyId: agency.id, clientId: "client-017", ownerUserId: "user-3", channel: "phone", status: "new", startedAt: "2026-04-10T08:50:00-05:00", endedAt: "2026-04-10T09:02:00-05:00", summary: "Missing renewal packet follow-up call reached voicemail and needs another attempt.", medicareScope: "Intake support", routingState: "blocked", detectedTopics: ["missing_document_follow_up"], retirementInterestDetected: false, nextStep: "Retry outreach and confirm mailing address." },
  { id: "conv-020", agencyId: agency.id, clientId: "client-018", ownerUserId: "user-2", channel: "phone", status: "in_review", startedAt: "2026-04-10T10:10:00-05:00", endedAt: "2026-04-10T10:34:00-05:00", summary: "Client discussed a premium increase and asked whether retirement income could support future costs.", medicareScope: "Medigap review", routingState: "awaiting_review", detectedTopics: ["premium_increase", "retirement_income_interest"], retirementInterestDetected: true, nextStep: "Compliance review, then separate consented follow-up if appropriate." },
  { id: "conv-021", agencyId: agency.id, clientId: "client-019", ownerUserId: "user-3", channel: "service_call", status: "closed", startedAt: "2026-04-10T14:20:00-05:00", endedAt: "2026-04-10T14:33:00-05:00", summary: "Beneficiary contact update completed after a family change.", medicareScope: "Service only", routingState: "complete", detectedTopics: ["service_call"], retirementInterestDetected: false, nextStep: "Closed." },
  { id: "conv-022", agencyId: agency.id, clientId: "client-020", ownerUserId: "user-5", channel: "phone", status: "routed", startedAt: "2026-04-11T09:05:00-05:00", endedAt: "2026-04-11T09:39:00-05:00", summary: "Follow-up after spouse loss included a request to talk later about stable retirement income.", medicareScope: "Medigap review", routingState: "ready_to_route", detectedTopics: ["spouse_passed_away", "retirement_income_interest"], retirementInterestDetected: true, nextStep: "Open separate consent request and assign licensed follow-up only after approval." },
  { id: "conv-023", agencyId: agency.id, clientId: "client-021", ownerUserId: "user-3", channel: "service_call", status: "closed", startedAt: "2026-04-11T10:15:00-05:00", endedAt: "2026-04-11T10:24:00-05:00", summary: "Document request call surfaced an upcoming CD maturity, but no retirement discussion occurred.", medicareScope: "Service only", routingState: "complete", detectedTopics: ["service_call", "cd_maturing"], retirementInterestDetected: true, nextStep: "Log the signal only and wait for explicit consent if follow-up is desired." },
  { id: "conv-024", agencyId: agency.id, clientId: "client-022", ownerUserId: "user-5", channel: "phone", status: "closed", startedAt: "2026-04-11T13:00:00-05:00", endedAt: "2026-04-11T13:23:00-05:00", summary: "Annual Medigap review completed with neutral plan education and no flags.", medicareScope: "Medigap review", routingState: "complete", detectedTopics: ["medigap_review"], retirementInterestDetected: false, nextStep: "Closed after notes saved." },
  { id: "conv-025", agencyId: agency.id, clientId: "client-023", ownerUserId: "user-2", channel: "phone", status: "in_review", startedAt: "2026-04-11T15:05:00-05:00", endedAt: "2026-04-11T15:32:00-05:00", summary: "Client asked turning-65 enrollment timing questions and whether delaying work changes SEP options.", medicareScope: "Turning 65 intake", routingState: "awaiting_review", detectedTopics: ["turning_65"], retirementInterestDetected: false, nextStep: "Send enrollment timing summary." },
  { id: "conv-026", agencyId: agency.id, clientId: "client-024", ownerUserId: "user-5", channel: "phone", status: "routed", startedAt: "2026-04-12T08:55:00-05:00", endedAt: "2026-04-12T09:21:00-05:00", summary: "Volatility concerns came up during a rate review and the client asked for a later retirement-income discussion.", medicareScope: "Medigap review", routingState: "ready_to_route", detectedTopics: ["market_risk_concern", "retirement_income_interest"], retirementInterestDetected: true, nextStep: "Move to a separate consented workflow." },
  { id: "conv-027", agencyId: agency.id, clientId: "client-025", ownerUserId: "user-3", channel: "service_call", status: "closed", startedAt: "2026-04-12T10:45:00-05:00", endedAt: "2026-04-12T10:59:00-05:00", summary: "Missing document reminder completed and signature instructions resent.", medicareScope: "Service only", routingState: "complete", detectedTopics: ["missing_document_follow_up", "service_call"], retirementInterestDetected: false, nextStep: "Closed." },
  { id: "conv-028", agencyId: agency.id, clientId: "client-002", ownerUserId: "user-4", channel: "phone", status: "closed", startedAt: "2026-04-12T13:10:00-05:00", endedAt: "2026-04-12T13:22:00-05:00", summary: "Compliance reviewer confirmed neutral language in the Medigap review notes.", medicareScope: "Compliance follow-up", routingState: "complete", detectedTopics: ["compliance_review"], retirementInterestDetected: false, nextStep: "Closed." },
  { id: "conv-029", agencyId: agency.id, clientId: "client-004", ownerUserId: "user-4", channel: "phone", status: "in_review", startedAt: "2026-04-13T09:40:00-05:00", endedAt: "2026-04-13T09:58:00-05:00", summary: "Manual review needed after an agent phrase could be read as steering on Medicare Advantage.", medicareScope: "Compliance follow-up", routingState: "awaiting_review", detectedTopics: ["medicare_advantage_question", "compliance_review"], retirementInterestDetected: false, nextStep: "Finalize QA notes and coach the agent." },
  { id: "conv-030", agencyId: agency.id, clientId: "client-007", ownerUserId: "user-6", channel: "phone", status: "routed", startedAt: "2026-04-13T10:30:00-05:00", endedAt: "2026-04-13T10:52:00-05:00", summary: "Separate licensed follow-up consent discussion after a CD maturity signal.", medicareScope: "Separate follow-up only", routingState: "ready_to_route", detectedTopics: ["cd_maturing", "retirement_income_interest", "consent"], retirementInterestDetected: true, nextStep: "Await digital consent completion." },
  { id: "conv-031", agencyId: agency.id, clientId: "client-008", ownerUserId: "user-6", channel: "phone", status: "routed", startedAt: "2026-04-13T11:45:00-05:00", endedAt: "2026-04-13T12:07:00-05:00", summary: "Separate follow-up review requested after the client asked about retirement income stability.", medicareScope: "Separate follow-up only", routingState: "ready_to_route", detectedTopics: ["retirement_income_interest", "consent"], retirementInterestDetected: true, nextStep: "Assign licensed owner after consent verification." },
  { id: "conv-032", agencyId: agency.id, clientId: "client-009", ownerUserId: "user-6", channel: "phone", status: "new", startedAt: "2026-04-13T13:20:00-05:00", endedAt: "2026-04-13T13:34:00-05:00", summary: "Client wants a later conversation about market risk and retirement income planning, not during Medicare review.", medicareScope: "Separate follow-up only", routingState: "blocked", detectedTopics: ["market_risk_concern", "retirement_income_interest"], retirementInterestDetected: true, nextStep: "Need explicit consent before any outreach." },
  { id: "conv-033", agencyId: agency.id, clientId: "client-014", ownerUserId: "user-6", channel: "phone", status: "new", startedAt: "2026-04-14T08:55:00-05:00", endedAt: "2026-04-14T09:14:00-05:00", summary: "Budget pressure and premium increase prompted interest in a separate retirement follow-up.", medicareScope: "Separate follow-up only", routingState: "blocked", detectedTopics: ["premium_increase", "retirement_income_interest"], retirementInterestDetected: true, nextStep: "Obtain separate consent first." },
  { id: "conv-034", agencyId: agency.id, clientId: "client-018", ownerUserId: "user-4", channel: "phone", status: "in_review", startedAt: "2026-04-14T10:05:00-05:00", endedAt: "2026-04-14T10:26:00-05:00", summary: "Compliance QA on affordability language after a premium increase discussion.", medicareScope: "Compliance follow-up", routingState: "awaiting_review", detectedTopics: ["premium_increase", "compliance_review"], retirementInterestDetected: false, nextStep: "Complete QA review." },
  { id: "conv-035", agencyId: agency.id, clientId: "client-020", ownerUserId: "user-6", channel: "phone", status: "routed", startedAt: "2026-04-14T11:15:00-05:00", endedAt: "2026-04-14T11:38:00-05:00", summary: "Separate consent request accepted after spouse-loss service work uncovered retirement-income questions.", medicareScope: "Separate follow-up only", routingState: "ready_to_route", detectedTopics: ["spouse_passed_away", "retirement_income_interest", "consent"], retirementInterestDetected: true, nextStep: "Assign to licensed follow-up specialist." },
  { id: "conv-036", agencyId: agency.id, clientId: "client-021", ownerUserId: "user-6", channel: "phone", status: "closed", startedAt: "2026-04-14T13:05:00-05:00", endedAt: "2026-04-14T13:19:00-05:00", summary: "Client confirmed no separate follow-up is needed after the CD maturity signal was logged.", medicareScope: "Separate follow-up only", routingState: "complete", detectedTopics: ["cd_maturing"], retirementInterestDetected: true, nextStep: "Close signal with no action." },
  { id: "conv-037", agencyId: agency.id, clientId: "client-024", ownerUserId: "user-6", channel: "phone", status: "routed", startedAt: "2026-04-15T09:00:00-05:00", endedAt: "2026-04-15T09:21:00-05:00", summary: "Client gave permission for a future discussion on income stability after market volatility concerns.", medicareScope: "Separate follow-up only", routingState: "ready_to_route", detectedTopics: ["market_risk_concern", "retirement_income_interest", "consent"], retirementInterestDetected: true, nextStep: "Assign and schedule licensed follow-up." },
  { id: "conv-038", agencyId: agency.id, clientId: "client-011", ownerUserId: "user-3", channel: "service_call", status: "closed", startedAt: "2026-04-15T10:10:00-05:00", endedAt: "2026-04-15T10:20:00-05:00", summary: "Second missing-document reminder completed and secure upload instructions resent.", medicareScope: "Service only", routingState: "complete", detectedTopics: ["missing_document_follow_up", "service_call"], retirementInterestDetected: false, nextStep: "Closed." },
  { id: "conv-039", agencyId: agency.id, clientId: "client-017", ownerUserId: "user-3", channel: "service_call", status: "new", startedAt: "2026-04-15T14:25:00-05:00", endedAt: "2026-04-15T14:33:00-05:00", summary: "Client called back about the missing renewal packet and requested another copy.", medicareScope: "Service only", routingState: "blocked", detectedTopics: ["missing_document_follow_up", "service_call"], retirementInterestDetected: false, nextStep: "Mail and email replacement documents." },
  { id: "conv-040", agencyId: agency.id, clientId: "client-023", ownerUserId: "user-2", channel: "phone", status: "closed", startedAt: "2026-04-16T09:35:00-05:00", endedAt: "2026-04-16T09:52:00-05:00", summary: "SEP timing call completed with clear guidance on enrollment windows and no product discussion.", medicareScope: "Turning 65 intake", routingState: "complete", detectedTopics: ["turning_65"], retirementInterestDetected: false, nextStep: "Closed." }
];

const conversationMessages: ConversationMessage[] = [
  { id: "msg-001", conversationId: "conv-001", speakerType: "agent", speakerName: "Alex Rivera", utterance: "We can review your turning-65 timeline first and keep the discussion focused on Medicare enrollment steps.", spokenAt: "2026-04-03T09:01:00-05:00", sequenceNumber: 1 },
  { id: "msg-002", conversationId: "conv-001", speakerType: "client", speakerName: "Margaret Ellis", utterance: "I mostly want to understand when I need to start looking at supplement coverage.", spokenAt: "2026-04-03T09:03:00-05:00", sequenceNumber: 2 },
  { id: "msg-003", conversationId: "conv-001", speakerType: "agent", speakerName: "Alex Rivera", utterance: "We can outline the timing and paperwork without choosing a plan today.", spokenAt: "2026-04-03T09:05:00-05:00", sequenceNumber: 3 },
  { id: "msg-004", conversationId: "conv-004", speakerType: "client", speakerName: "Patricia Boone", utterance: "My pharmacy said one of my prescriptions may move tiers next year.", spokenAt: "2026-04-05T11:05:00-05:00", sequenceNumber: 1 },
  { id: "msg-005", conversationId: "conv-004", speakerType: "agent", speakerName: "Alex Rivera", utterance: "I can document that Part D question and explain the review process without recommending a plan change on this call.", spokenAt: "2026-04-05T11:08:00-05:00", sequenceNumber: 2 },
  { id: "msg-006", conversationId: "conv-005", speakerType: "agent", speakerName: "Alex Rivera", utterance: "I want to stay neutral here and explain how Medicare Advantage generally works before any next step.", spokenAt: "2026-04-05T13:36:00-05:00", sequenceNumber: 1 },
  { id: "msg-007", conversationId: "conv-006", speakerType: "system", speakerName: "Call Recorder", utterance: "Updated SOA could not be found in the intake packet.", spokenAt: "2026-04-06T09:39:00-05:00", sequenceNumber: 1 },
  { id: "msg-008", conversationId: "conv-008", speakerType: "client", speakerName: "Robert Callahan", utterance: "Since my wife passed, I am also worried about how to make income last.", spokenAt: "2026-04-12T10:18:00-05:00", sequenceNumber: 1 },
  { id: "msg-009", conversationId: "conv-008", speakerType: "agent", speakerName: "Riley Torres", utterance: "We should keep that topic separate from your Medicare review and only continue later if you want a separate conversation.", spokenAt: "2026-04-12T10:20:00-05:00", sequenceNumber: 2 },
  { id: "msg-010", conversationId: "conv-009", speakerType: "client", speakerName: "Linda Navarro", utterance: "One of my CDs is coming due and I am not sure what makes sense now.", spokenAt: "2026-04-07T08:47:00-05:00", sequenceNumber: 1 },
  { id: "msg-011", conversationId: "conv-010", speakerType: "client", speakerName: "Kenneth Yates", utterance: "These rate increases have me thinking more broadly about retirement income.", spokenAt: "2026-04-07T11:23:00-05:00", sequenceNumber: 1 },
  { id: "msg-012", conversationId: "conv-010", speakerType: "agent", speakerName: "Alex Rivera", utterance: "I can note that concern, but any income-related conversation has to be separate and permission-based.", spokenAt: "2026-04-07T11:25:00-05:00", sequenceNumber: 2 },
  { id: "msg-013", conversationId: "conv-011", speakerType: "client", speakerName: "Marilyn Shah", utterance: "The market swings lately have me more worried than I used to be.", spokenAt: "2026-04-07T14:11:00-05:00", sequenceNumber: 1 },
  { id: "msg-014", conversationId: "conv-013", speakerType: "service", speakerName: "Mia Chen", utterance: "I still do not show the signed intake page, so I am calling to help you finish the packet.", spokenAt: "2026-04-08T10:23:00-05:00", sequenceNumber: 1 },
  { id: "msg-015", conversationId: "conv-014", speakerType: "client", speakerName: "Helen Park", utterance: "I turn 65 in August and want to make sure I do not miss the right window.", spokenAt: "2026-04-08T13:08:00-05:00", sequenceNumber: 1 },
  { id: "msg-016", conversationId: "conv-016", speakerType: "client", speakerName: "Carol Dorsey", utterance: "Between rates going up and groceries, I am worried about the bigger picture now.", spokenAt: "2026-04-09T09:42:00-05:00", sequenceNumber: 1 },
  { id: "msg-017", conversationId: "conv-020", speakerType: "system", speakerName: "QA Scanner", utterance: "Review affordability language for possible cross-sell risk.", spokenAt: "2026-04-10T10:36:00-05:00", sequenceNumber: 1 },
  { id: "msg-018", conversationId: "conv-022", speakerType: "client", speakerName: "Martha Quinn", utterance: "I am fine to keep Medicare separate, but I may need help talking through income later.", spokenAt: "2026-04-11T09:21:00-05:00", sequenceNumber: 1 },
  { id: "msg-019", conversationId: "conv-023", speakerType: "client", speakerName: "Leonard Price", utterance: "I have a CD renewing soon, though I do not want to get into that on this call.", spokenAt: "2026-04-11T10:18:00-05:00", sequenceNumber: 1 },
  { id: "msg-020", conversationId: "conv-024", speakerType: "agent", speakerName: "Riley Torres", utterance: "Today we stayed with supplement review only and confirmed your current paperwork is complete.", spokenAt: "2026-04-11T13:18:00-05:00", sequenceNumber: 1 },
  { id: "msg-021", conversationId: "conv-026", speakerType: "client", speakerName: "Gloria Bennett", utterance: "If the market keeps moving like this, I would want a different conversation later.", spokenAt: "2026-04-12T09:03:00-05:00", sequenceNumber: 1 },
  { id: "msg-022", conversationId: "conv-029", speakerType: "system", speakerName: "QA Scanner", utterance: "Potentially directive phrasing detected in Medicare Advantage explanation.", spokenAt: "2026-04-13T09:59:00-05:00", sequenceNumber: 1 },
  { id: "msg-023", conversationId: "conv-030", speakerType: "agent", speakerName: "Casey Monroe", utterance: "This is a separate follow-up discussion and not part of your Medicare review.", spokenAt: "2026-04-13T10:33:00-05:00", sequenceNumber: 1 },
  { id: "msg-024", conversationId: "conv-031", speakerType: "client", speakerName: "Kenneth Yates", utterance: "I am comfortable having someone licensed call me later if that is separate.", spokenAt: "2026-04-13T11:57:00-05:00", sequenceNumber: 1 },
  { id: "msg-025", conversationId: "conv-032", speakerType: "client", speakerName: "Marilyn Shah", utterance: "I want to think about that first before anyone follows up.", spokenAt: "2026-04-13T13:29:00-05:00", sequenceNumber: 1 },
  { id: "msg-026", conversationId: "conv-035", speakerType: "agent", speakerName: "Casey Monroe", utterance: "I have your separate permission recorded for a later conversation with a licensed person.", spokenAt: "2026-04-14T11:22:00-05:00", sequenceNumber: 1 },
  { id: "msg-027", conversationId: "conv-036", speakerType: "client", speakerName: "Leonard Price", utterance: "For now I just wanted the document, not a follow-up conversation.", spokenAt: "2026-04-14T13:11:00-05:00", sequenceNumber: 1 },
  { id: "msg-028", conversationId: "conv-037", speakerType: "client", speakerName: "Gloria Bennett", utterance: "Yes, I would like a separate call later on retirement income stability.", spokenAt: "2026-04-15T09:08:00-05:00", sequenceNumber: 1 },
  { id: "msg-029", conversationId: "conv-038", speakerType: "service", speakerName: "Mia Chen", utterance: "I resent the signature instructions while we were on the phone.", spokenAt: "2026-04-15T10:14:00-05:00", sequenceNumber: 1 },
  { id: "msg-030", conversationId: "conv-040", speakerType: "agent", speakerName: "Alex Rivera", utterance: "I covered the enrollment windows only and did not discuss products on this call.", spokenAt: "2026-04-16T09:48:00-05:00", sequenceNumber: 1 }
];

const transcriptSummaries: TranscriptSummary[] = [
  { id: "ts-001", conversationId: "conv-001", clientId: "client-001", createdAt: "2026-04-03T09:26:00-05:00", summary: "Turning-65 intake completed with a neutral explanation of timeline and supplement process.", detectedTopics: ["turning_65", "consent"], complianceReviewStatus: "clear", consentStatus: "complete", nextAction: "Prepare intake checklist." },
  { id: "ts-002", conversationId: "conv-004", clientId: "client-003", createdAt: "2026-04-05T11:23:00-05:00", summary: "Part D formulary question documented without product recommendation.", detectedTopics: ["part_d_question"], complianceReviewStatus: "clear", consentStatus: "complete", nextAction: "Send Part D education note." },
  { id: "ts-003", conversationId: "conv-005", clientId: "client-004", createdAt: "2026-04-05T13:58:00-05:00", summary: "Medicare Advantage question needs compliance review because wording could be read as directional.", detectedTopics: ["medicare_advantage_question", "compliance_review"], complianceReviewStatus: "review_required", consentStatus: "complete", nextAction: "Manual QA review." },
  { id: "ts-004", conversationId: "conv-006", clientId: "client-005", createdAt: "2026-04-06T09:40:00-05:00", summary: "Premium increase review blocked because refreshed scope documentation is missing.", detectedTopics: ["premium_increase", "consent"], complianceReviewStatus: "watch", consentStatus: "missing", nextAction: "Refresh SOA." },
  { id: "ts-005", conversationId: "conv-008", clientId: "client-006", createdAt: "2026-04-12T10:36:00-05:00", summary: "Spouse-loss follow-up remained Medicare-focused and logged a separate retirement-income concern.", detectedTopics: ["spouse_passed_away", "retirement_income_interest"], complianceReviewStatus: "watch", consentStatus: "complete", nextAction: "Create separate consented workflow." },
  { id: "ts-006", conversationId: "conv-009", clientId: "client-007", createdAt: "2026-04-07T08:53:00-05:00", summary: "Service call surfaced a CD maturity comment; no follow-up authorized yet.", detectedTopics: ["service_call", "cd_maturing"], complianceReviewStatus: "clear", consentStatus: "complete", nextAction: "Log signal only." },
  { id: "ts-007", conversationId: "conv-010", clientId: "client-008", createdAt: "2026-04-07T11:44:00-05:00", summary: "Affordability concerns expanded into retirement income questions and were separated from Medicare notes.", detectedTopics: ["medigap_review", "retirement_income_interest"], complianceReviewStatus: "watch", consentStatus: "complete", nextAction: "Request separate consent." },
  { id: "ts-008", conversationId: "conv-011", clientId: "client-009", createdAt: "2026-04-07T14:28:00-05:00", summary: "Market-risk concern identified during a supplement review and documented for separate follow-up.", detectedTopics: ["market_risk_concern", "retirement_income_interest"], complianceReviewStatus: "watch", consentStatus: "complete", nextAction: "Offer separate licensed follow-up with consent." },
  { id: "ts-009", conversationId: "conv-013", clientId: "client-011", createdAt: "2026-04-08T10:34:00-05:00", summary: "Intake packet is still incomplete and contact documentation needs follow-up.", detectedTopics: ["missing_document_follow_up", "consent"], complianceReviewStatus: "watch", consentStatus: "pending", nextAction: "Collect missing packet pages." },
  { id: "ts-010", conversationId: "conv-016", clientId: "client-014", createdAt: "2026-04-09T10:00:00-05:00", summary: "Budget pressure created a retirement-income signal that must stay outside the Medicare workflow.", detectedTopics: ["premium_increase", "retirement_income_interest"], complianceReviewStatus: "watch", consentStatus: "complete", nextAction: "Create separate workflow if consent is granted." },
  { id: "ts-011", conversationId: "conv-020", clientId: "client-018", createdAt: "2026-04-10T10:35:00-05:00", summary: "Premium increase discussion may have drifted close to financial-product language and needs QA review.", detectedTopics: ["premium_increase", "retirement_income_interest", "compliance_review"], complianceReviewStatus: "review_required", consentStatus: "complete", nextAction: "Manual QA then separate consented workflow if appropriate." },
  { id: "ts-012", conversationId: "conv-022", clientId: "client-020", createdAt: "2026-04-11T09:40:00-05:00", summary: "Spouse-loss review surfaced a clear request for later retirement-income help.", detectedTopics: ["spouse_passed_away", "retirement_income_interest"], complianceReviewStatus: "watch", consentStatus: "complete", nextAction: "Send separate consent request." },
  { id: "ts-013", conversationId: "conv-026", clientId: "client-024", createdAt: "2026-04-12T09:24:00-05:00", summary: "Volatility concern recorded; client asked for a later, separate conversation on income stability.", detectedTopics: ["market_risk_concern", "retirement_income_interest"], complianceReviewStatus: "clear", consentStatus: "complete", nextAction: "Initiate separate workflow." },
  { id: "ts-014", conversationId: "conv-030", clientId: "client-007", createdAt: "2026-04-13T10:54:00-05:00", summary: "Separate consent discussion held after a CD maturity signal from an earlier service call.", detectedTopics: ["cd_maturing", "consent"], complianceReviewStatus: "clear", consentStatus: "pending", nextAction: "Wait for explicit digital consent." },
  { id: "ts-015", conversationId: "conv-037", clientId: "client-024", createdAt: "2026-04-15T09:24:00-05:00", summary: "Client gave permission for a future licensed follow-up about income stability.", detectedTopics: ["market_risk_concern", "retirement_income_interest", "consent"], complianceReviewStatus: "clear", consentStatus: "complete", nextAction: "Assign licensed specialist." }
];

const consentRecords: ConsentRecord[] = [
  { id: "consent-001", clientId: "client-001", conversationId: "conv-001", consentType: "recording", status: "granted", capturedAt: "2026-04-03T09:00:30-05:00", captureMethod: "verbal on recorded line", evidenceRef: "REC-0403-0900", evidenceComplete: true, notes: "Recording consent captured before intake." },
  { id: "consent-002", clientId: "client-001", conversationId: "conv-001", consentType: "soa", status: "granted", capturedAt: "2026-04-03T09:02:00-05:00", captureMethod: "electronic intake form", evidenceRef: "SOA-0403-001", evidenceComplete: true, notes: "Scope covers turning-65 intake." },
  { id: "consent-003", clientId: "client-002", conversationId: "conv-003", consentType: "recording", status: "granted", capturedAt: "2026-04-04T10:15:30-05:00", captureMethod: "verbal on recorded line", evidenceRef: "REC-0404-1015", evidenceComplete: true, notes: "Annual review call." },
  { id: "consent-004", clientId: "client-003", conversationId: "conv-004", consentType: "recording", status: "granted", capturedAt: "2026-04-05T11:00:30-05:00", captureMethod: "verbal on recorded line", evidenceRef: "REC-0405-1100", evidenceComplete: true, notes: "Part D question call." },
  { id: "consent-005", clientId: "client-004", conversationId: "conv-005", consentType: "recording", status: "granted", capturedAt: "2026-04-05T13:30:20-05:00", captureMethod: "verbal on recorded line", evidenceRef: "REC-0405-1330", evidenceComplete: true, notes: "Advantage question logged." },
  { id: "consent-006", clientId: "client-005", conversationId: "conv-006", consentType: "soa", status: "pending", capturedAt: "2026-04-06T09:38:30-05:00", captureMethod: "missing refresh", evidenceRef: "SOA-PENDING-005", evidenceComplete: false, notes: "Prior scope expired." },
  { id: "consent-007", clientId: "client-006", conversationId: "conv-008", consentType: "recording", status: "granted", capturedAt: "2026-04-12T10:05:20-05:00", captureMethod: "verbal on recorded line", evidenceRef: "REC-0412-1005", evidenceComplete: true, notes: "Household update review." },
  { id: "consent-008", clientId: "client-007", conversationId: "conv-009", consentType: "contact", status: "granted", capturedAt: "2026-04-07T08:41:00-05:00", captureMethod: "service request intake", evidenceRef: "CONTACT-007", evidenceComplete: true, notes: "Permission to return service call." },
  { id: "consent-009", clientId: "client-008", conversationId: "conv-010", consentType: "recording", status: "granted", capturedAt: "2026-04-07T11:10:30-05:00", captureMethod: "verbal on recorded line", evidenceRef: "REC-0407-1110", evidenceComplete: true, notes: "Medigap affordability review." },
  { id: "consent-010", clientId: "client-009", conversationId: "conv-011", consentType: "recording", status: "granted", capturedAt: "2026-04-07T14:00:25-05:00", captureMethod: "verbal on recorded line", evidenceRef: "REC-0407-1400", evidenceComplete: true, notes: "Market-risk note captured." },
  { id: "consent-011", clientId: "client-011", conversationId: "conv-013", consentType: "contact", status: "pending", capturedAt: "2026-04-08T10:32:00-05:00", captureMethod: "manual follow-up request", evidenceRef: "CONTACT-PENDING-011", evidenceComplete: false, notes: "Packet not complete." },
  { id: "consent-012", clientId: "client-012", conversationId: "conv-014", consentType: "recording", status: "granted", capturedAt: "2026-04-08T13:05:15-05:00", captureMethod: "verbal on recorded line", evidenceRef: "REC-0408-1305", evidenceComplete: true, notes: "Turning-65 call." },
  { id: "consent-013", clientId: "client-014", conversationId: "conv-016", consentType: "recording", status: "granted", capturedAt: "2026-04-09T09:30:20-05:00", captureMethod: "verbal on recorded line", evidenceRef: "REC-0409-0930", evidenceComplete: true, notes: "Budget review call." },
  { id: "consent-014", clientId: "client-018", conversationId: "conv-020", consentType: "recording", status: "granted", capturedAt: "2026-04-10T10:10:20-05:00", captureMethod: "verbal on recorded line", evidenceRef: "REC-0410-1010", evidenceComplete: true, notes: "Premium increase review." },
  { id: "consent-015", clientId: "client-020", conversationId: "conv-022", followupWorkflowId: "fw-006", linkedOpportunityId: "fw-006", consentType: "retirement_follow_up", status: "pending", capturedAt: "2026-04-11T09:40:00-05:00", captureMethod: "separate digital request sent", evidenceRef: "RET-PENDING-020", evidenceComplete: false, notes: "Separate follow-up requested after spouse-loss review." },
  { id: "consent-016", clientId: "client-007", conversationId: "conv-030", followupWorkflowId: "fw-001", linkedOpportunityId: "fw-001", consentType: "retirement_follow_up", status: "pending", capturedAt: "2026-04-13T10:53:00-05:00", captureMethod: "digital consent pending", evidenceRef: "RET-PENDING-007", evidenceComplete: false, notes: "CD maturity follow-up consent pending." },
  { id: "consent-017", clientId: "client-008", conversationId: "conv-031", followupWorkflowId: "fw-002", linkedOpportunityId: "fw-002", consentType: "retirement_follow_up", status: "granted", capturedAt: "2026-04-13T12:05:00-05:00", captureMethod: "verbal and documented", evidenceRef: "RET-008-GRANTED", evidenceComplete: true, notes: "Separate consent granted." },
  { id: "consent-018", clientId: "client-024", conversationId: "conv-037", followupWorkflowId: "fw-010", linkedOpportunityId: "fw-010", consentType: "retirement_follow_up", status: "granted", capturedAt: "2026-04-15T09:22:00-05:00", captureMethod: "recorded verbal authorization", evidenceRef: "RET-024-GRANTED", evidenceComplete: true, notes: "Licensed follow-up permitted." },
  { id: "consent-019", clientId: "client-023", conversationId: "conv-040", consentType: "recording", status: "granted", capturedAt: "2026-04-16T09:35:10-05:00", captureMethod: "verbal on recorded line", evidenceRef: "REC-0416-0935", evidenceComplete: true, notes: "SEP timing call." },
  { id: "consent-020", clientId: "client-025", conversationId: "conv-027", consentType: "contact", status: "granted", capturedAt: "2026-04-12T10:46:00-05:00", captureMethod: "service request intake", evidenceRef: "CONTACT-025", evidenceComplete: true, notes: "Reminder permission documented." }
];

const complianceFlags: ComplianceFlag[] = [
  { id: "flag-001", conversationId: "conv-005", clientId: "client-004", flagType: "needs_human_review", severity: "medium", status: "open", rationale: "Advantage explanation should be checked for neutral phrasing.", detectedBy: "system", flaggedAt: "2026-04-05T13:57:00-05:00", recommendedAction: "Manual QA review." },
  { id: "flag-002", conversationId: "conv-006", clientId: "client-005", flagType: "missing_consent", severity: "high", status: "open", rationale: "Updated SOA is not on file for the premium review.", detectedBy: "human", flaggedAt: "2026-04-06T09:39:00-05:00", recommendedAction: "Refresh SOA before next call." },
  { id: "flag-003", conversationId: "conv-008", clientId: "client-006", flagType: "cross_sell_risk", severity: "high", status: "open", rationale: "Income concern surfaced during Medicare review and must be separated.", detectedBy: "system", flaggedAt: "2026-04-12T10:35:00-05:00", recommendedAction: "Create separate workflow only." },
  { id: "flag-004", conversationId: "conv-009", clientId: "client-007", flagType: "cross_sell_risk", severity: "medium", status: "resolved", rationale: "CD maturity signal logged during service call.", detectedBy: "system", flaggedAt: "2026-04-07T08:53:00-05:00", recommendedAction: "Monitor unless consent is granted." },
  { id: "flag-005", conversationId: "conv-010", clientId: "client-008", flagType: "cross_sell_risk", severity: "high", status: "open", rationale: "Retirement income concern needs separate consent.", detectedBy: "system", flaggedAt: "2026-04-07T11:44:00-05:00", recommendedAction: "Open separate consent request." },
  { id: "flag-006", conversationId: "conv-011", clientId: "client-009", flagType: "cross_sell_risk", severity: "medium", status: "open", rationale: "Market-risk concern should not stay in Medicare workflow.", detectedBy: "system", flaggedAt: "2026-04-07T14:28:00-05:00", recommendedAction: "Separate the note and request consent." },
  { id: "flag-007", conversationId: "conv-013", clientId: "client-011", flagType: "missing_consent", severity: "critical", status: "open", rationale: "Contact documentation and packet signatures remain incomplete.", detectedBy: "human", flaggedAt: "2026-04-08T10:34:00-05:00", recommendedAction: "Collect missing forms." },
  { id: "flag-008", conversationId: "conv-016", clientId: "client-014", flagType: "cross_sell_risk", severity: "medium", status: "open", rationale: "Budget concern created a broader financial planning question.", detectedBy: "system", flaggedAt: "2026-04-09T10:01:00-05:00", recommendedAction: "Use separate follow-up workflow only." },
  { id: "flag-009", conversationId: "conv-020", clientId: "client-018", flagType: "needs_human_review", severity: "high", status: "open", rationale: "Affordability language should be checked before any additional outreach.", detectedBy: "system", flaggedAt: "2026-04-10T10:35:00-05:00", recommendedAction: "Manual QA review." },
  { id: "flag-010", conversationId: "conv-022", clientId: "client-020", flagType: "cross_sell_risk", severity: "high", status: "open", rationale: "Spouse-loss conversation included a request for separate retirement follow-up.", detectedBy: "human", flaggedAt: "2026-04-11T09:40:00-05:00", recommendedAction: "Separate consent workflow." },
  { id: "flag-011", conversationId: "conv-023", clientId: "client-021", flagType: "cross_sell_risk", severity: "low", status: "resolved", rationale: "CD maturity mention logged during service call.", detectedBy: "system", flaggedAt: "2026-04-11T10:25:00-05:00", recommendedAction: "No outreach without consent." },
  { id: "flag-012", conversationId: "conv-026", clientId: "client-024", flagType: "cross_sell_risk", severity: "medium", status: "open", rationale: "Volatility concern moved beyond Medicare scope.", detectedBy: "system", flaggedAt: "2026-04-12T09:24:00-05:00", recommendedAction: "Use consented follow-up workflow." },
  { id: "flag-013", conversationId: "conv-029", clientId: "client-004", flagType: "unsupported_claim", severity: "high", status: "open", rationale: "Potentially directive phrase around Medicare Advantage needs review.", detectedBy: "system", flaggedAt: "2026-04-13T09:59:00-05:00", recommendedAction: "Coach agent and finalize QA." },
  { id: "flag-014", conversationId: "conv-030", clientId: "client-007", flagType: "missing_consent", severity: "medium", status: "open", rationale: "Separate follow-up consent request has not been completed.", detectedBy: "human", flaggedAt: "2026-04-13T10:54:00-05:00", recommendedAction: "Wait for explicit consent." },
  { id: "flag-015", conversationId: "conv-032", clientId: "client-009", flagType: "missing_consent", severity: "medium", status: "open", rationale: "No explicit follow-up consent yet.", detectedBy: "human", flaggedAt: "2026-04-13T13:35:00-05:00", recommendedAction: "Do not assign outreach." },
  { id: "flag-016", conversationId: "conv-033", clientId: "client-014", flagType: "cross_sell_risk", severity: "medium", status: "open", rationale: "Retirement-income topic detected after premium affordability review.", detectedBy: "system", flaggedAt: "2026-04-14T09:15:00-05:00", recommendedAction: "Separate workflow and consent." },
  { id: "flag-017", conversationId: "conv-035", clientId: "client-020", flagType: "needs_human_review", severity: "low", status: "resolved", rationale: "Verified that separate consent was captured before assignment.", detectedBy: "human", flaggedAt: "2026-04-14T11:40:00-05:00", recommendedAction: "Proceed with licensed follow-up." },
  { id: "flag-018", conversationId: "conv-037", clientId: "client-024", flagType: "cross_sell_risk", severity: "medium", status: "resolved", rationale: "Separated from Medicare workflow after consent capture.", detectedBy: "human", flaggedAt: "2026-04-15T09:25:00-05:00", recommendedAction: "Assign licensed specialist." },
  { id: "flag-019", conversationId: "conv-039", clientId: "client-017", flagType: "missing_consent", severity: "low", status: "open", rationale: "Service callback permission should be refreshed before another attempt.", detectedBy: "human", flaggedAt: "2026-04-15T14:34:00-05:00", recommendedAction: "Refresh contact consent." },
  { id: "flag-020", conversationId: "conv-040", clientId: "client-023", flagType: "needs_human_review", severity: "low", status: "dismissed", rationale: "QA reviewed the call and found no compliance issue.", detectedBy: "human", flaggedAt: "2026-04-16T10:00:00-05:00", recommendedAction: "No further action." }
];

const opportunitySignals: OpportunitySignal[] = [
  { id: "sig-001", clientId: "client-006", conversationId: "conv-008", signalType: "estate_change", detectedAt: "2026-04-12T10:35:00-05:00", source: "transcript_summary", confidence: "high", signalSummary: "Client raised household income concerns after spouse loss.", recommendedWorkflow: "separate_followup", status: "workflow_created" },
  { id: "sig-002", clientId: "client-007", conversationId: "conv-009", signalType: "cd_maturing", detectedAt: "2026-04-07T08:53:00-05:00", source: "service_call", confidence: "medium", signalSummary: "CD maturity mentioned during service call.", recommendedWorkflow: "separate_followup", status: "workflow_created" },
  { id: "sig-003", clientId: "client-008", conversationId: "conv-010", signalType: "retirement_income_interest", detectedAt: "2026-04-07T11:44:00-05:00", source: "transcript_summary", confidence: "high", signalSummary: "Client wants to discuss retirement income pressure from supplement costs.", recommendedWorkflow: "separate_followup", status: "workflow_created" },
  { id: "sig-004", clientId: "client-009", conversationId: "conv-011", signalType: "market_risk_concern", detectedAt: "2026-04-07T14:28:00-05:00", source: "transcript_summary", confidence: "high", signalSummary: "Market volatility concern surfaced during supplement review.", recommendedWorkflow: "separate_followup", status: "workflow_created" },
  { id: "sig-005", clientId: "client-014", conversationId: "conv-016", signalType: "premium_pressure", detectedAt: "2026-04-09T10:01:00-05:00", source: "transcript_summary", confidence: "medium", signalSummary: "Budget pressure may lead to retirement-income discussion.", recommendedWorkflow: "separate_followup", status: "workflow_created" },
  { id: "sig-006", clientId: "client-018", conversationId: "conv-020", signalType: "premium_pressure", detectedAt: "2026-04-10T10:35:00-05:00", source: "transcript_summary", confidence: "medium", signalSummary: "Premium increase concern expanded into future-income question.", recommendedWorkflow: "separate_followup", status: "reviewed" },
  { id: "sig-007", clientId: "client-020", conversationId: "conv-022", signalType: "estate_change", detectedAt: "2026-04-11T09:40:00-05:00", source: "transcript_summary", confidence: "high", signalSummary: "Spouse-loss review created a clear request for separate financial follow-up.", recommendedWorkflow: "separate_followup", status: "workflow_created" },
  { id: "sig-008", clientId: "client-021", conversationId: "conv-023", signalType: "cd_maturing", detectedAt: "2026-04-11T10:25:00-05:00", source: "service_call", confidence: "low", signalSummary: "CD maturity mentioned but client did not request follow-up.", recommendedWorkflow: "monitor_only", status: "reviewed" },
  { id: "sig-009", clientId: "client-024", conversationId: "conv-026", signalType: "market_risk_concern", detectedAt: "2026-04-12T09:24:00-05:00", source: "transcript_summary", confidence: "high", signalSummary: "Client wants a later income stability conversation after market volatility discussion.", recommendedWorkflow: "separate_followup", status: "workflow_created" },
  { id: "sig-010", clientId: "client-007", conversationId: "conv-030", signalType: "cd_maturing", detectedAt: "2026-04-13T10:54:00-05:00", source: "manual_note", confidence: "high", signalSummary: "Separate follow-up consent discussion held after CD maturity signal.", recommendedWorkflow: "separate_followup", status: "workflow_created" },
  { id: "sig-011", clientId: "client-009", conversationId: "conv-032", signalType: "market_risk_concern", detectedAt: "2026-04-13T13:35:00-05:00", source: "manual_note", confidence: "medium", signalSummary: "Client wants time before deciding on separate follow-up.", recommendedWorkflow: "separate_followup", status: "reviewed" },
  { id: "sig-012", clientId: "client-024", conversationId: "conv-037", signalType: "retirement_income_interest", detectedAt: "2026-04-15T09:24:00-05:00", source: "transcript_summary", confidence: "high", signalSummary: "Explicit request for later licensed discussion on retirement income stability.", recommendedWorkflow: "separate_followup", status: "workflow_created" }
];

const followupWorkflows: FollowupWorkflow[] = [
  { id: "fw-001", clientId: "client-007", sourceConversationId: "conv-030", opportunitySignalId: "sig-010", type: "retirement_income_follow_up", status: "awaiting_consent", explicitConsentStatus: "pending", interestSummary: "CD maturity concern was logged separately from Medicare service work.", nextStep: "Wait for explicit digital consent.", requestedAt: "2026-04-13T10:54:00-05:00", lastUpdatedAt: "2026-04-13T10:54:00-05:00" },
  { id: "fw-002", clientId: "client-008", sourceConversationId: "conv-031", opportunitySignalId: "sig-003", type: "retirement_income_follow_up", status: "ready_for_assignment", explicitConsentStatus: "granted", interestSummary: "Client wants a later licensed call about retirement income pressure.", nextStep: "Assign licensed owner and schedule outreach.", requestedAt: "2026-04-13T12:05:00-05:00", lastUpdatedAt: "2026-04-13T12:05:00-05:00" },
  { id: "fw-003", clientId: "client-009", sourceConversationId: "conv-032", opportunitySignalId: "sig-004", type: "retirement_income_follow_up", status: "awaiting_consent", explicitConsentStatus: "missing", interestSummary: "Market-risk concern captured, but the client has not opted into follow-up.", nextStep: "No outreach until explicit consent is granted.", requestedAt: "2026-04-13T13:35:00-05:00", lastUpdatedAt: "2026-04-13T13:35:00-05:00" },
  { id: "fw-004", clientId: "client-014", sourceConversationId: "conv-033", opportunitySignalId: "sig-005", type: "retirement_income_follow_up", status: "awaiting_consent", explicitConsentStatus: "pending", interestSummary: "Budget pressure suggests a separate retirement-income discussion may be helpful.", nextStep: "Send separate consent link.", requestedAt: "2026-04-14T09:15:00-05:00", lastUpdatedAt: "2026-04-14T09:15:00-05:00" },
  { id: "fw-005", clientId: "client-018", sourceConversationId: "conv-020", opportunitySignalId: "sig-006", type: "retirement_income_follow_up", status: "detected", explicitConsentStatus: "missing", interestSummary: "Premium increase and affordability concerns may warrant a later discussion.", nextStep: "Compliance review before consent outreach.", requestedAt: "2026-04-10T10:35:00-05:00", lastUpdatedAt: "2026-04-10T10:35:00-05:00" },
  { id: "fw-006", clientId: "client-020", sourceConversationId: "conv-022", opportunitySignalId: "sig-007", type: "retirement_income_follow_up", status: "awaiting_consent", explicitConsentStatus: "pending", interestSummary: "Spouse-loss follow-up created a separate request for retirement-income guidance.", nextStep: "Await digital consent and then assign licensed staff.", requestedAt: "2026-04-11T09:40:00-05:00", lastUpdatedAt: "2026-04-11T09:40:00-05:00" },
  { id: "fw-007", clientId: "client-024", sourceConversationId: "conv-026", opportunitySignalId: "sig-009", type: "retirement_income_follow_up", status: "detected", explicitConsentStatus: "missing", interestSummary: "Market volatility concern documented; no follow-up yet.", nextStep: "Request separate permission if the client wants to continue.", requestedAt: "2026-04-12T09:24:00-05:00", lastUpdatedAt: "2026-04-12T09:24:00-05:00" },
  { id: "fw-008", clientId: "client-006", sourceConversationId: "conv-008", opportunitySignalId: "sig-001", type: "retirement_income_follow_up", status: "assigned", explicitConsentStatus: "granted", assignedUserId: "user-6", interestSummary: "Household income concern after spouse loss was moved into a separate licensed workflow.", nextStep: "Complete assigned follow-up call.", requestedAt: "2026-04-12T10:36:00-05:00", lastUpdatedAt: "2026-04-13T08:00:00-05:00" },
  { id: "fw-009", clientId: "client-021", sourceConversationId: "conv-036", opportunitySignalId: "sig-008", type: "retirement_income_follow_up", status: "closed_no_action", explicitConsentStatus: "revoked", interestSummary: "CD maturity signal logged, but the client declined separate follow-up.", nextStep: "Keep note only.", requestedAt: "2026-04-11T10:25:00-05:00", lastUpdatedAt: "2026-04-14T13:20:00-05:00" },
  { id: "fw-010", clientId: "client-024", sourceConversationId: "conv-037", opportunitySignalId: "sig-012", type: "retirement_income_follow_up", status: "assigned", explicitConsentStatus: "granted", assignedUserId: "user-6", interestSummary: "Client requested a future licensed conversation on retirement-income stability.", nextStep: "Prepare outreach notes and confirm appointment.", requestedAt: "2026-04-15T09:24:00-05:00", lastUpdatedAt: "2026-04-15T09:30:00-05:00" }
];

const qaReviews: QaReview[] = [
  { id: "qa-001", conversationId: "conv-003", reviewerUserId: "user-4", score: 95, outcome: "pass", reviewedAt: "2026-04-04T15:00:00-05:00", summary: "Neutral Medigap review with complete documentation." },
  { id: "qa-002", conversationId: "conv-005", reviewerUserId: "user-4", score: 79, outcome: "pass_with_notes", reviewedAt: "2026-04-06T08:30:00-05:00", summary: "Advantage explanation acceptable after note revision." },
  { id: "qa-003", conversationId: "conv-010", reviewerUserId: "user-4", score: 84, outcome: "pass_with_notes", reviewedAt: "2026-04-08T16:00:00-05:00", summary: "Income signal correctly separated from Medicare discussion." },
  { id: "qa-004", conversationId: "conv-020", reviewerUserId: "user-4", score: 68, outcome: "escalate", reviewedAt: "2026-04-11T08:10:00-05:00", summary: "Affordability wording requires coaching before next outreach." },
  { id: "qa-005", conversationId: "conv-024", reviewerUserId: "user-4", score: 98, outcome: "pass", reviewedAt: "2026-04-11T15:00:00-05:00", summary: "Clean review with no compliance issues." }
];

const tasks: Task[] = [
  { id: "task-001", clientId: "client-005", sourceType: "consent", sourceId: "consent-006", title: "Refresh expired SOA", queue: "intake", status: "open", priority: "high", assignedUserId: "user-5", dueAt: "2026-04-17T12:00:00-05:00" },
  { id: "task-002", clientId: "client-011", sourceType: "consent", sourceId: "consent-011", title: "Collect missing intake packet", queue: "service", status: "in_progress", priority: "urgent", assignedUserId: "user-3", dueAt: "2026-04-17T10:30:00-05:00" },
  { id: "task-003", clientId: "client-004", sourceType: "qa_review", sourceId: "qa-002", title: "Review Advantage language for neutrality", queue: "compliance", status: "open", priority: "high", assignedUserId: "user-4", dueAt: "2026-04-17T15:00:00-05:00" },
  { id: "task-004", clientId: "client-006", sourceType: "follow_up_opportunity", sourceId: "fw-008", title: "Complete licensed follow-up after spouse-loss review", queue: "follow_up", status: "in_progress", priority: "high", assignedUserId: "user-6", dueAt: "2026-04-18T11:00:00-05:00" },
  { id: "task-005", clientId: "client-007", sourceType: "follow_up_opportunity", sourceId: "fw-001", title: "Monitor pending follow-up consent", queue: "follow_up", status: "open", priority: "normal", assignedUserId: "user-1", dueAt: "2026-04-18T14:00:00-05:00" },
  { id: "task-006", clientId: "client-008", sourceType: "follow_up_opportunity", sourceId: "fw-002", title: "Assign licensed retirement follow-up owner", queue: "follow_up", status: "open", priority: "high", assignedUserId: "user-1", dueAt: "2026-04-18T09:30:00-05:00" },
  { id: "task-007", clientId: "client-009", sourceType: "follow_up_opportunity", sourceId: "fw-003", title: "Hold outreach until consent exists", queue: "follow_up", status: "blocked", priority: "normal", assignedUserId: "user-1", dueAt: "2026-04-18T16:00:00-05:00" },
  { id: "task-008", clientId: "client-014", sourceType: "follow_up_opportunity", sourceId: "fw-004", title: "Send separate consent request", queue: "follow_up", status: "in_progress", priority: "high", assignedUserId: "user-1", dueAt: "2026-04-17T17:00:00-05:00" },
  { id: "task-009", clientId: "client-018", sourceType: "conversation", sourceId: "conv-020", title: "Complete QA on premium-increase call", queue: "compliance", status: "open", priority: "urgent", assignedUserId: "user-4", dueAt: "2026-04-17T13:00:00-05:00" },
  { id: "task-010", clientId: "client-020", sourceType: "follow_up_opportunity", sourceId: "fw-006", title: "Await and verify separate digital consent", queue: "follow_up", status: "open", priority: "high", assignedUserId: "user-1", dueAt: "2026-04-18T10:30:00-05:00" },
  { id: "task-011", clientId: "client-021", sourceType: "follow_up_opportunity", sourceId: "fw-009", title: "Document no-action closure", queue: "follow_up", status: "done", priority: "low", assignedUserId: "user-6", dueAt: "2026-04-14T15:00:00-05:00" },
  { id: "task-012", clientId: "client-024", sourceType: "follow_up_opportunity", sourceId: "fw-010", title: "Prepare assigned licensed follow-up", queue: "follow_up", status: "open", priority: "high", assignedUserId: "user-6", dueAt: "2026-04-18T11:30:00-05:00" },
  { id: "task-013", clientId: "client-001", sourceType: "conversation", sourceId: "conv-001", title: "Finalize turning-65 intake notes", queue: "intake", status: "done", priority: "normal", assignedUserId: "user-2", dueAt: "2026-04-04T12:00:00-05:00" },
  { id: "task-014", clientId: "client-003", sourceType: "conversation", sourceId: "conv-004", title: "Send Part D educational follow-up", queue: "service", status: "done", priority: "normal", assignedUserId: "user-3", dueAt: "2026-04-06T09:00:00-05:00" },
  { id: "task-015", clientId: "client-017", sourceType: "conversation", sourceId: "conv-039", title: "Send replacement renewal packet", queue: "service", status: "open", priority: "normal", assignedUserId: "user-3", dueAt: "2026-04-17T16:30:00-05:00" },
  { id: "task-016", clientId: "client-023", sourceType: "conversation", sourceId: "conv-040", title: "Archive SEP timing note", queue: "intake", status: "done", priority: "low", assignedUserId: "user-2", dueAt: "2026-04-16T12:00:00-05:00" },
  { id: "task-017", clientId: "client-004", sourceType: "conversation", sourceId: "conv-029", title: "Coach agent on neutral phrasing", queue: "compliance", status: "open", priority: "normal", assignedUserId: "user-4", dueAt: "2026-04-18T13:30:00-05:00" },
  { id: "task-018", clientId: "client-025", sourceType: "conversation", sourceId: "conv-027", title: "Confirm signature reminder completed", queue: "service", status: "done", priority: "low", assignedUserId: "user-3", dueAt: "2026-04-13T11:30:00-05:00" },
  { id: "task-019", clientId: "client-012", sourceType: "conversation", sourceId: "conv-014", title: "Send turning-65 checklist", queue: "intake", status: "open", priority: "normal", assignedUserId: "user-2", dueAt: "2026-04-17T12:30:00-05:00" },
  { id: "task-020", clientId: "client-024", sourceType: "follow_up_opportunity", sourceId: "fw-007", title: "Review signal before consent outreach", queue: "follow_up", status: "in_progress", priority: "normal", assignedUserId: "user-1", dueAt: "2026-04-17T18:00:00-05:00" }
];

const auditEvents: AuditEvent[] = [
  { id: "audit-001", entityType: "consent", entityId: "consent-015", action: "requested", actorUserId: "user-1", eventAt: "2026-04-11T09:41:00-05:00", detail: "Separate digital consent request sent after spouse-loss follow-up.", sourceContext: "conv-022", consentStatusSnapshot: "pending", nextAction: "Await client action." },
  { id: "audit-002", entityType: "follow_up_opportunity", entityId: "fw-001", action: "created", actorUserId: "user-1", eventAt: "2026-04-13T10:54:00-05:00", detail: "Follow-up workflow created from CD maturity signal.", sourceContext: "sig-010", consentStatusSnapshot: "pending", nextAction: "Wait for explicit consent." },
  { id: "audit-003", entityType: "consent", entityId: "consent-017", action: "granted", actorUserId: "user-6", eventAt: "2026-04-13T12:05:00-05:00", detail: "Separate follow-up consent documented on a recorded line.", sourceContext: "conv-031", consentStatusSnapshot: "granted", nextAction: "Assign licensed owner." },
  { id: "audit-004", entityType: "follow_up_opportunity", entityId: "fw-002", action: "ready_for_assignment", actorUserId: "user-6", eventAt: "2026-04-13T12:06:00-05:00", detail: "Workflow advanced after consent was verified.", sourceContext: "sig-003", consentStatusSnapshot: "granted", nextAction: "Assign licensed owner." },
  { id: "audit-005", entityType: "follow_up_opportunity", entityId: "fw-008", action: "assigned", actorUserId: "user-1", eventAt: "2026-04-13T08:00:00-05:00", detail: "Licensed follow-up assigned after spouse-loss review.", sourceContext: "sig-001", consentStatusSnapshot: "granted", nextAction: "Complete follow-up call." },
  { id: "audit-006", entityType: "task", entityId: "task-004", action: "status_changed", actorUserId: "user-6", eventAt: "2026-04-13T08:05:00-05:00", detail: "Task moved to in progress.", sourceContext: "fw-008", nextAction: "Complete outreach." },
  { id: "audit-007", entityType: "consent", entityId: "consent-018", action: "granted", actorUserId: "user-6", eventAt: "2026-04-15T09:22:00-05:00", detail: "Recorded verbal authorization captured for separate follow-up.", sourceContext: "conv-037", consentStatusSnapshot: "granted", nextAction: "Assign specialist." },
  { id: "audit-008", entityType: "follow_up_opportunity", entityId: "fw-010", action: "assigned", actorUserId: "user-1", eventAt: "2026-04-15T09:30:00-05:00", detail: "Licensed specialist assigned to follow-up workflow.", sourceContext: "sig-012", consentStatusSnapshot: "granted", nextAction: "Prepare appointment." },
  { id: "audit-009", entityType: "follow_up_opportunity", entityId: "fw-009", action: "closed_no_action", actorUserId: "user-6", eventAt: "2026-04-14T13:20:00-05:00", detail: "Client declined separate follow-up after signal review.", sourceContext: "sig-008", consentStatusSnapshot: "revoked", nextAction: "Retain note only." },
  { id: "audit-010", entityType: "consent", entityId: "consent-006", action: "pending", actorUserId: "user-5", eventAt: "2026-04-06T09:39:30-05:00", detail: "Scope refresh required before more Medicare review.", sourceContext: "conv-006", consentStatusSnapshot: "pending", nextAction: "Collect updated SOA." },
  { id: "audit-011", entityType: "follow_up_opportunity", entityId: "fw-006", action: "created", actorUserId: "user-1", eventAt: "2026-04-11T09:41:30-05:00", detail: "Separate workflow created from spouse-loss income concern.", sourceContext: "sig-007", consentStatusSnapshot: "pending", nextAction: "Await consent." },
  { id: "audit-012", entityType: "qa_review", entityId: "qa-004", action: "escalated", actorUserId: "user-4", eventAt: "2026-04-11T08:10:00-05:00", detail: "Affordability language escalated for coaching.", sourceContext: "conv-020", nextAction: "Finalize review notes." }
];

const followUpOpportunities = followupWorkflows;
const transcriptEntries = conversationMessages;

export const initialDemoData: DemoDataState = {
  agency,
  users,
  clients,
  conversations,
  conversationMessages,
  transcriptEntries,
  transcriptSummaries,
  consentRecords,
  complianceFlags,
  opportunitySignals,
  followupWorkflows,
  followUpOpportunities,
  qaReviews,
  tasks,
  auditEvents,
  currentUserId: "user-1"
};

export const fakeDataCounts = {
  agencies: 1,
  users: users.length,
  clients: clients.length,
  conversations: conversations.length,
  transcriptSummaries: transcriptSummaries.length,
  consentRecords: consentRecords.length,
  complianceFlags: complianceFlags.length,
  opportunitySignals: opportunitySignals.length,
  followupWorkflows: followupWorkflows.length,
  tasks: tasks.length,
  auditEvents: auditEvents.length
};
